### ISSUE TITLE
Package.resolved needs to be removed and added to gitignore

### ISSUE THREAD

**Issue by kdawgwilk** [Moya/Harvey#18]
Checking in the `Package.resolved` can be problematic for other packages that depend on this package

**Comment by AndrewSB** [comment]
That goes against my intuition. Can you show discussion or examples of why it might be problematic?

**Comment by pedrovereza** [comment]
I'm also curious on what kind of problems this may cause. [The proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0175-package-manager-revised-dependency-resolution.md#proposed-solution) mentions it shouldn't cause issues (highlight by me):

> Resolved versions will always be recorded by the package manager. Some users may chose to add the Package.resolved file to their package's .gitignore file. When this file is checked in, it allows a team to coordinate on what versions of the dependencies they should use. If this file is gitignored, each user will separately choose when to get new versions based on when they run the swift package update command, and new users will start with the latest eligible version of each dependency. Either way, **for a package which is a dependency of other packages (e.g. a library package), that package's Package.resolved file will not have any effect on its client packages.**

**Comment by kdawgwilk** [comment]
I have been following the Vapor development community for some time now and they have always chosen not to check them in.  I had assumed that there was a good reason for it but it could possibly be just a preference

**Comment by orta** [comment]
Lockfiles should always be checked in, in every programming environment I've worked on so far. Here's the best summary of why: https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

**Comment by kdawgwilk** [comment]
Yeah lockfiles make perfect sense for the end user of the library but adding lockfiles to each library seemed like it could cause dependency hell because each library had a specific version pinned and would conflict with others that had a different version pinned.  But it appears that the resolved  file is ignored for all packages except the top level package which resolves my concerns

**Comment by AndrewSB** [comment]
If you’re up for it, I’d recommend opening the inverse issue over at vapor. I’d love to hear if you find out why they choose not to check in their lockfile

**Comment by kdawgwilk** [comment]
@tanner0101 Just mentioning you here for your thoughts on why Vapor projects choose to add the `Package.resolved` to `.gitignore` on all library projects

**Comment by tanner0101** [comment]
We don't have the Package.resolved file git ignored for our templates, so anyone creating a Vapor project will commit the lockfile by default. However, our libraries _do_ ignore the resolved file so that we can be sure CI is always testing against the latest dependencies. We discussed this decision quite a bit with the SPM team before doing it and they seemed to think it was a sensible approach.
